FROM alpine:3.7

RUN apk update && \
    apk add make cmake clang python3 go valgrind cloc
RUN apk add g++  # TODO: remove
COPY . /misaka
# ENV CMAKE_C_COMPILER=clang  # TODO: enable
ENV CXX=clang++
WORKDIR /misaka
RUN make install && \
    make test && \
    make go_example && \
    make check && \
    cloc src/misaka
# TODO: python_example
